version: 0.2

environment_variables:
  plaintext:
    "PIPENV_DEV": 1
    "ZAPPA_ENV": "dev"

phases:
  install:
    commands:
      - echo Installing pipenv...
      - pip install pipenv
      - echo Pipenv installed
      - echo Installing depencencies
      - pipenv install -d
      - echo Dependencies installed
  build:
    commands:
      - echo Deployment started
      - cd ontmoet
      - pipenv run zappa update dev
      - echo Deployment finished