version: 0.2

environment_variables:
  plaintext:
    "PIPENV_DEV": 1
    "ZAPPA_ENV": "dev"

phases:
  install:
    commands:
      - echo Setting up virtualenv
      - python -m venv venv
      - source venv/bin/activate
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - echo Installing dependencies finished
  build:
    commands:
      - echo Deployment started
      - cd ontmoet
      - zappa update dev
      - echo Deployment finished